// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/admin/jeux/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/games/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin" | "/login" | "/admin/jeux/edit/:id" | "/games/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/admin.jeux.edit.$id.tsx": {
    id: "routes/admin.jeux.edit.$id";
    page: "/admin/jeux/edit/:id";
  };
  "routes/games.$id.tsx": {
    id: "routes/games.$id";
    page: "/games/:id";
  };
};