// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/jeux/edit/:id": {
    params: {
      "id": string;
    };
  };
  "/games/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/admin" | "/admin/jeux/edit/:id" | "/games/:id";
  };
  "./pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "./pages/login.tsx": {
    id: "pages/login";
    page: "/login";
  };
  "./pages/admin.tsx": {
    id: "pages/admin";
    page: "/admin";
  };
  "./pages/admin.jeux.edit.$id.tsx": {
    id: "pages/admin.jeux.edit.$id";
    page: "/admin/jeux/edit/:id";
  };
  "./pages/games.$id.tsx": {
    id: "pages/games.$id";
    page: "/games/:id";
  };
};