// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/casa": {
    params: {};
  };
  "/games/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/casa" | "/games/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/casa.tsx": {
    id: "routes/casa";
    page: "/casa";
  };
  "routes/games.$id.tsx": {
    id: "routes/games.$id";
    page: "/games/:id";
  };
};