name: Build, Test & Deploy Backend

on:
  push:
    paths:
      - 'api/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run API Tests
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd api
          npm ci

      - name: Run tests with coverage
        run: |
          cd api
          npm run test

  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: devtonyqc/fiches-backend:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 72.11.148.122
          username: admin
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/admin/Fiches-culturelles/api
            docker compose pull
            docker compose up -d
