name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        cd api
        npm ci

    - name: Run tests (with coverage & badge)
      run: |
        cd api
        npm run test

    - name: Commit & push badge if changed
      run: |
        cd api
        if [[ `git status --porcelain coverage-badge.svg` ]]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add coverage-badge.svg
          git commit -m "chore(ci): update coverage badge [skip ci]"
          git push
        fi

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Filter paths
      id: filter
      uses: dorny/paths-filter@v3
      with:
        filters: |
          backend:
            - 'api/**'
          frontend:
            - 'src/**'

    - name: Deploy API
      if: steps.filter.outputs.backend == 'true'
      run: |
        ssh -o StrictHostKeyChecking=no admin@72.11.148.122 "
          cd /home/admin/Fiches-culturelles/api &&
          git pull origin main &&
          npm ci --omit=dev &&
          pm2 reload api
        "

    - name: Deploy Frontend
      if: steps.filter.outputs.frontend == 'true'
      run: |
        ssh -o StrictHostKeyChecking=no admin@72.11.148.122 "
          cd /home/admin/Fiches-culturelles/src/my-app &&
          git pull origin main &&
          npm ci &&
          npm run build &&
          rsync -av --delete build/client/ /var/www/html/
        "
