name: Build & Deploy Frontend

on:
  push:
    paths:
      - 'src/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true
          tags: devtonyqc/fiches-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 72.11.148.122
          username: admin
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/admin/Fiches-culturelles/src
            docker compose pull
            docker compose up -d
